# input = [u'Tooth and Tail Free Download', u'http://oceanofgames.com/tooth-and-tail-free-download/', u'Tested on Windows 7 64-Bit', u'Operating System: Windows Vista/7/8/8.1/10', u'CPU: 2 GHz Processor', u'RAM: 2GB', u'Setup Size: 712.9MB', u'Hard Disk Space: 2GB', u'Talisman Digital Edition The Dragon Free Download', u'http://oceanofgames.com/talisman-digital-edition-the-dragon-free-download/', u'Tested on Windows 7 64-Bit', u'Operating System: Windows Vista/7/8/8.1/10', u'CPU: 2.0GHz Intel Dual Core processor or later.', u'RAM: 2GB', u'Setup Size: 580.4MB', u'Hard Disk Space: 2GB', u'The Warlock of Firetop Mountain Free Download', u'http://oceanofgames.com/the-warlock-of-firetop-mountain-free-download/', u'Tested on Windows 7 64-Bit', u'Operating System: Windows Vista/7/8/8.1/10', u'CPU: 1.5 GHz', u'RAM: 4GB', u'Setup Size: 784MB', u'Hard Disk Space: 2GB', u'Tyranny Bastards Wound Free Download', u'http://oceanofgames.com/tyranny-bastards-wound-free-download/', u'Tested on Windows 7 64-Bit', u'Operating System: Windows Vista/7/8/8.1/10', u'CPU: Intel Core 2 Quad Q9505 @ 2.80 GHz / AMD Athlon II X4 840 @ 3.10 GHz', u'RAM: 6GB', u'Setup Size: 7.9GB', u'Hard Disk Space: 15GB', u'Star Story The Horizon Escape Free Download', u'http://oceanofgames.com/star-story-the-horizon-escape-free-download/', u'Tested on Windows 7 64-Bit', u'Operating System: Windows Vista/7/8/8.1/10', u'CPU: 2.0 GHz+ Dual Core Processor or higher', u'RAM: 2GB', u'Setup Size: 746.1MB', u'Hard Disk Space: 4GB', u'Arma 3 Laws of War Free Download', u'http://oceanofgames.com/arma-3-laws-of-war-free-download/', u'Tested on Windows 7 64-Bit', u'Operating System: Windows Vista/7/8/8.1/10', u'CPU: Intel Dual-Core 2.4 GHz or AMD Dual-Core Athlon 2.5 GHz', u'RAM: 4GB', u'Setup Size: 26GB', u'Hard Disk Space: 30GB', u'Please Knock on My Door Free Download', u'http://oceanofgames.com/please-knock-on-my-door-free-download/', u'Tested on Windows 7 64-Bit', u'Operating System: Windows Vista/7/8/8.1/10', u'CPU: Intel Core i7-2700K @ 3.5GHz or equivalent', u'RAM: 8GB', u'Setup Size: 689.6MB', u'Hard Disk Space: 4GB']
# append_list = []
# s= ([input[i:i+8] for i in range(0, len(input), 8)])
# for i in s:
# 	print(len(i))


for i in range(1,10):
	print i
	print type(i)